# React to a comment on PRs
name: emoji-spammer
on:
  issue_comment:
    types: [created]

permissions: write-all
#  contents: read
#  issues: write

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - id: spamyspam
        name: Spam some emoji on the comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
          set -eux
          echo "+1" | gh api \
            -X POST \
            --header "Accept:application/vnd.github.v3+json" \
            /repos/VladimirSlavik/testing/pulls/comments/${{ github.event.comment.id }}/reactions \
            --include \
            --input -
